/// Les 99 noms d'Allah (al-asma' al-husna), dans l'ordre de la narration
/// rapportée par at-Tirmidhi.
///
/// Les sens français et anglais sont des traductions usuelles, données à
/// titre indicatif : à faire relire par une personne qualifiée avant
/// publication.
library;

typedef DivineName = ({String arabic, String transliteration, String fr, String en});

const asmaUlHusna = <DivineName>[
  (
    arabic: 'الرَّحْمَنُ',
    transliteration: 'Ar-Rahman',
    fr: 'Le Tout Miséricordieux',
    en: 'The Entirely Merciful',
  ),
  (
    arabic: 'الرَّحِيمُ',
    transliteration: 'Ar-Rahim',
    fr: 'Le Très Miséricordieux',
    en: 'The Especially Merciful',
  ),
  (arabic: 'الْمَلِكُ', transliteration: 'Al-Malik', fr: 'Le Souverain', en: 'The King'),
  (
    arabic: 'الْقُدُّوسُ',
    transliteration: 'Al-Quddus',
    fr: 'Le Pur, le Saint',
    en: 'The Most Holy',
  ),
  (
    arabic: 'السَّلَامُ',
    transliteration: 'As-Salam',
    fr: 'La Paix, Celui qui est exempt de tout défaut',
    en: 'The Source of Peace',
  ),
  (
    arabic: 'الْمُؤْمِنُ',
    transliteration: "Al-Mu'min",
    fr: 'Celui qui accorde la sécurité',
    en: 'The Granter of Security',
  ),
  (
    arabic: 'الْمُهَيْمِنُ',
    transliteration: 'Al-Muhaymin',
    fr: 'Le Préservateur, le Témoin vigilant',
    en: 'The Guardian',
  ),
  (
    arabic: 'الْعَزِيزُ',
    transliteration: "Al-'Aziz",
    fr: "Le Tout-Puissant, l'Invincible",
    en: 'The Almighty',
  ),
  (
    arabic: 'الْجَبَّارُ',
    transliteration: 'Al-Jabbar',
    fr: 'Le Contraignant, Celui qui répare',
    en: 'The Compeller',
  ),
  (
    arabic: 'الْمُتَكَبِّرُ',
    transliteration: 'Al-Mutakabbir',
    fr: 'Le Suprêmement Grand',
    en: 'The Supreme in Greatness',
  ),
  (arabic: 'الْخَالِقُ', transliteration: 'Al-Khaliq', fr: 'Le Créateur', en: 'The Creator'),
  (
    arabic: 'الْبَارِئُ',
    transliteration: "Al-Bari'",
    fr: 'Celui qui donne l’existence',
    en: 'The Originator',
  ),
  (
    arabic: 'الْمُصَوِّرُ',
    transliteration: 'Al-Musawwir',
    fr: 'Celui qui donne forme',
    en: 'The Fashioner',
  ),
  (
    arabic: 'الْغَفَّارُ',
    transliteration: 'Al-Ghaffar',
    fr: 'Le Grand Pardonneur',
    en: 'The Ever-Forgiving',
  ),
  (
    arabic: 'الْقَهَّارُ',
    transliteration: 'Al-Qahhar',
    fr: 'Le Dominateur suprême',
    en: 'The Subduer',
  ),
  (arabic: 'الْوَهَّابُ', transliteration: 'Al-Wahhab', fr: 'Le Donateur', en: 'The Bestower'),
  (arabic: 'الرَّزَّاقُ', transliteration: 'Ar-Razzaq', fr: 'Le Pourvoyeur', en: 'The Provider'),
  (
    arabic: 'الْفَتَّاحُ',
    transliteration: 'Al-Fattah',
    fr: 'Celui qui ouvre, le Juge',
    en: 'The Opener',
  ),
  (arabic: 'الْعَلِيمُ', transliteration: "Al-'Alim", fr: "L'Omniscient", en: 'The All-Knowing'),
  (
    arabic: 'الْقَابِضُ',
    transliteration: 'Al-Qabid',
    fr: 'Celui qui restreint',
    en: 'The Withholder',
  ),
  (
    arabic: 'الْبَاسِطُ',
    transliteration: 'Al-Basit',
    fr: 'Celui qui étend Ses dons',
    en: 'The Extender',
  ),
  (arabic: 'الْخَافِضُ', transliteration: 'Al-Khafid', fr: 'Celui qui abaisse', en: 'The Abaser'),
  (arabic: 'الرَّافِعُ', transliteration: "Ar-Rafi'", fr: 'Celui qui élève', en: 'The Exalter'),
  (
    arabic: 'الْمُعِزُّ',
    transliteration: "Al-Mu'izz",
    fr: 'Celui qui honore',
    en: 'The Bestower of Honour',
  ),
  (
    arabic: 'الْمُذِلُّ',
    transliteration: 'Al-Mudhill',
    fr: 'Celui qui humilie',
    en: 'The Humiliator',
  ),
  (
    arabic: 'السَّمِيعُ',
    transliteration: "As-Sami'",
    fr: "L'Audient, Celui qui entend tout",
    en: 'The All-Hearing',
  ),
  (
    arabic: 'الْبَصِيرُ',
    transliteration: 'Al-Basir',
    fr: 'Le Clairvoyant, Celui qui voit tout',
    en: 'The All-Seeing',
  ),
  (arabic: 'الْحَكَمُ', transliteration: 'Al-Hakam', fr: 'Le Juge', en: 'The Judge'),
  (arabic: 'الْعَدْلُ', transliteration: "Al-'Adl", fr: 'Le Juste', en: 'The Just'),
  (
    arabic: 'اللَّطِيفُ',
    transliteration: 'Al-Latif',
    fr: 'Le Doux, le Subtil',
    en: 'The Subtle, the Kind',
  ),
  (
    arabic: 'الْخَبِيرُ',
    transliteration: 'Al-Khabir',
    fr: 'Le Parfaitement Informé',
    en: 'The All-Aware',
  ),
  (arabic: 'الْحَلِيمُ', transliteration: 'Al-Halim', fr: 'Le Longanime', en: 'The Forbearing'),
  (arabic: 'الْعَظِيمُ', transliteration: "Al-'Azim", fr: "L'Immense", en: 'The Magnificent'),
  (
    arabic: 'الْغَفُورُ',
    transliteration: 'Al-Ghafur',
    fr: 'Le Pardonneur',
    en: 'The All-Forgiving',
  ),
  (
    arabic: 'الشَّكُورُ',
    transliteration: 'Ash-Shakur',
    fr: 'Le Reconnaissant',
    en: 'The Appreciative',
  ),
  (arabic: 'الْعَلِيُّ', transliteration: "Al-'Aliyy", fr: 'Le Très-Haut', en: 'The Most High'),
  (arabic: 'الْكَبِيرُ', transliteration: 'Al-Kabir', fr: 'Le Grand', en: 'The Most Great'),
  (arabic: 'الْحَفِيظُ', transliteration: 'Al-Hafiz', fr: 'Le Gardien', en: 'The Preserver'),
  (
    arabic: 'الْمُقِيتُ',
    transliteration: 'Al-Muqit',
    fr: 'Celui qui nourrit et maintient',
    en: 'The Nourisher',
  ),
  (
    arabic: 'الْحَسِيبُ',
    transliteration: 'Al-Hasib',
    fr: 'Celui qui suffit, qui tient compte',
    en: 'The Reckoner',
  ),
  (arabic: 'الْجَلِيلُ', transliteration: 'Al-Jalil', fr: 'Le Majestueux', en: 'The Majestic'),
  (arabic: 'الْكَرِيمُ', transliteration: 'Al-Karim', fr: 'Le Généreux', en: 'The Generous'),
  (arabic: 'الرَّقِيبُ', transliteration: 'Ar-Raqib', fr: "L'Observateur", en: 'The Watchful'),
  (arabic: 'الْمُجِيبُ', transliteration: 'Al-Mujib', fr: 'Celui qui exauce', en: 'The Responsive'),
  (
    arabic: 'الْوَاسِعُ',
    transliteration: "Al-Wasi'",
    fr: 'Le Vaste, Celui qui englobe tout',
    en: 'The All-Encompassing',
  ),
  (arabic: 'الْحَكِيمُ', transliteration: 'Al-Hakim', fr: 'Le Sage', en: 'The Wise'),
  (arabic: 'الْوَدُودُ', transliteration: 'Al-Wadud', fr: 'Le Bien-Aimant', en: 'The Loving'),
  (arabic: 'الْمَجِيدُ', transliteration: 'Al-Majid', fr: 'Le Glorieux', en: 'The Glorious'),
  (
    arabic: 'الْبَاعِثُ',
    transliteration: "Al-Ba'ith",
    fr: 'Celui qui ressuscite',
    en: 'The Resurrector',
  ),
  (arabic: 'الشَّهِيدُ', transliteration: 'Ash-Shahid', fr: 'Le Témoin', en: 'The Witness'),
  (arabic: 'الْحَقُّ', transliteration: 'Al-Haqq', fr: 'La Vérité', en: 'The Truth'),
  (
    arabic: 'الْوَكِيلُ',
    transliteration: 'Al-Wakil',
    fr: "Le Garant, Celui à qui l'on s'en remet",
    en: 'The Trustee',
  ),
  (arabic: 'الْقَوِيُّ', transliteration: 'Al-Qawiyy', fr: 'Le Fort', en: 'The Strong'),
  (arabic: 'الْمَتِينُ', transliteration: 'Al-Matin', fr: "L'Inébranlable", en: 'The Firm'),
  (
    arabic: 'الْوَلِيُّ',
    transliteration: 'Al-Waliyy',
    fr: "Le Protecteur, l'Allié",
    en: 'The Protecting Friend',
  ),
  (
    arabic: 'الْحَمِيدُ',
    transliteration: 'Al-Hamid',
    fr: 'Le Digne de louange',
    en: 'The Praiseworthy',
  ),
  (
    arabic: 'الْمُحْصِي',
    transliteration: 'Al-Muhsi',
    fr: 'Celui qui dénombre tout',
    en: 'The Accounter',
  ),
  (
    arabic: 'الْمُبْدِئُ',
    transliteration: "Al-Mubdi'",
    fr: 'Celui qui commence la création',
    en: 'The Initiator',
  ),
  (
    arabic: 'الْمُعِيدُ',
    transliteration: "Al-Mu'id",
    fr: 'Celui qui la recommence',
    en: 'The Restorer',
  ),
  (
    arabic: 'الْمُحْيِي',
    transliteration: 'Al-Muhyi',
    fr: 'Celui qui donne la vie',
    en: 'The Giver of Life',
  ),
  (
    arabic: 'الْمُمِيتُ',
    transliteration: 'Al-Mumit',
    fr: 'Celui qui donne la mort',
    en: 'The Bringer of Death',
  ),
  (arabic: 'الْحَيُّ', transliteration: 'Al-Hayy', fr: 'Le Vivant', en: 'The Ever-Living'),
  (
    arabic: 'الْقَيُّومُ',
    transliteration: 'Al-Qayyum',
    fr: 'Celui qui subsiste par Lui-même',
    en: 'The Self-Subsisting',
  ),
  (
    arabic: 'الْوَاجِدُ',
    transliteration: 'Al-Wajid',
    fr: 'Celui à qui rien ne manque',
    en: 'The Finder',
  ),
  (arabic: 'الْمَاجِدُ', transliteration: 'Al-Majid', fr: "L'Illustre", en: 'The Illustrious'),
  (arabic: 'الْوَاحِدُ', transliteration: 'Al-Wahid', fr: "L'Unique", en: 'The One'),
  (arabic: 'الْأَحَدُ', transliteration: 'Al-Ahad', fr: "L'Un", en: 'The Unique'),
  (
    arabic: 'الصَّمَدُ',
    transliteration: 'As-Samad',
    fr: "L'Absolu, Celui dont tout dépend",
    en: 'The Eternal Refuge',
  ),
  (arabic: 'الْقَادِرُ', transliteration: 'Al-Qadir', fr: 'Le Capable', en: 'The Able'),
  (
    arabic: 'الْمُقْتَدِرُ',
    transliteration: 'Al-Muqtadir',
    fr: 'Le Tout-Puissant',
    en: 'The Powerful',
  ),
  (
    arabic: 'الْمُقَدِّمُ',
    transliteration: 'Al-Muqaddim',
    fr: 'Celui qui fait avancer',
    en: 'The Expediter',
  ),
  (
    arabic: 'الْمُؤَخِّرُ',
    transliteration: "Al-Mu'akhkhir",
    fr: 'Celui qui fait reculer',
    en: 'The Delayer',
  ),
  (arabic: 'الْأَوَّلُ', transliteration: 'Al-Awwal', fr: 'Le Premier', en: 'The First'),
  (arabic: 'الْآخِرُ', transliteration: 'Al-Akhir', fr: 'Le Dernier', en: 'The Last'),
  (arabic: 'الظَّاهِرُ', transliteration: 'Az-Zahir', fr: "L'Apparent", en: 'The Manifest'),
  (arabic: 'الْبَاطِنُ', transliteration: 'Al-Batin', fr: 'Le Caché', en: 'The Hidden'),
  (
    arabic: 'الْوَالِي',
    transliteration: 'Al-Wali',
    fr: 'Le Maître qui gouverne',
    en: 'The Governor',
  ),
  (
    arabic: 'الْمُتَعَالِي',
    transliteration: "Al-Muta'ali",
    fr: 'Le Très-Élevé',
    en: 'The Most Exalted',
  ),
  (
    arabic: 'الْبَرُّ',
    transliteration: 'Al-Barr',
    fr: 'Le Bienfaisant',
    en: 'The Source of Goodness',
  ),
  (
    arabic: 'التَّوَّابُ',
    transliteration: 'At-Tawwab',
    fr: 'Celui qui accepte le repentir',
    en: 'The Accepter of Repentance',
  ),
  (
    arabic: 'الْمُنْتَقِمُ',
    transliteration: 'Al-Muntaqim',
    fr: 'Celui qui châtie',
    en: 'The Avenger',
  ),
  (
    arabic: 'الْعَفُوُّ',
    transliteration: "Al-'Afuww",
    fr: "L'Indulgent, Celui qui efface les fautes",
    en: 'The Pardoner',
  ),
  (arabic: 'الرَّءُوفُ', transliteration: "Ar-Ra'uf", fr: 'Le Compatissant', en: 'The Most Kind'),
  (
    arabic: 'مَالِكُ الْمُلْكِ',
    transliteration: 'Malik al-Mulk',
    fr: 'Le Possesseur de la royauté',
    en: 'Owner of All Sovereignty',
  ),
  (
    arabic: 'ذُو الْجَلَالِ وَالْإِكْرَامِ',
    transliteration: 'Dhul-Jalali wal-Ikram',
    fr: 'Le Détenteur de la majesté et de la générosité',
    en: 'Lord of Majesty and Generosity',
  ),
  (arabic: 'الْمُقْسِطُ', transliteration: 'Al-Muqsit', fr: "L'Équitable", en: 'The Equitable'),
  (
    arabic: 'الْجَامِعُ',
    transliteration: "Al-Jami'",
    fr: 'Celui qui rassemble',
    en: 'The Gatherer',
  ),
  (
    arabic: 'الْغَنِيُّ',
    transliteration: 'Al-Ghaniyy',
    fr: 'Le Riche, qui se suffit à Lui-même',
    en: 'The Self-Sufficient',
  ),
  (
    arabic: 'الْمُغْنِي',
    transliteration: 'Al-Mughni',
    fr: 'Celui qui enrichit',
    en: 'The Enricher',
  ),
  (arabic: 'الْمَانِعُ', transliteration: "Al-Mani'", fr: 'Celui qui empêche', en: 'The Preventer'),
  (
    arabic: 'الضَّارُّ',
    transliteration: 'Ad-Darr',
    fr: 'Celui qui éprouve par le mal',
    en: 'The Distresser',
  ),
  (
    arabic: 'النَّافِعُ',
    transliteration: "An-Nafi'",
    fr: 'Celui qui accorde le bien',
    en: 'The Benefactor',
  ),
  (arabic: 'النُّورُ', transliteration: 'An-Nur', fr: 'La Lumière', en: 'The Light'),
  (arabic: 'الْهَادِي', transliteration: 'Al-Hadi', fr: 'Le Guide', en: 'The Guide'),
  (
    arabic: 'الْبَدِيعُ',
    transliteration: "Al-Badi'",
    fr: 'Le Créateur incomparable',
    en: 'The Incomparable Originator',
  ),
  (arabic: 'الْبَاقِي', transliteration: 'Al-Baqi', fr: 'Celui qui demeure', en: 'The Everlasting'),
  (arabic: 'الْوَارِثُ', transliteration: 'Al-Warith', fr: "L'Héritier", en: 'The Inheritor'),
  (
    arabic: 'الرَّشِيدُ',
    transliteration: 'Ar-Rashid',
    fr: 'Le Guide vers la droiture',
    en: 'The Guide to the Right Path',
  ),
  (arabic: 'الصَّبُورُ', transliteration: 'As-Sabur', fr: 'Le Patient', en: 'The Patient'),
];
